### ISSUE TITLE
ImportError: cannot import name 'config' from partially initialized module 'html2text' 

### ISSUE THREAD

**Issue by fengwu-coder** [unclecode/crawl4ai#160]
Traceback (most recent call last):
  File "C:\Users\57682\PycharmProjects\pythonProject\main.py", line 2, in <module>
    from crawl4ai import AsyncWebCrawler
  File "C:\Users\57682\PycharmProjects\pythonProject\venv\Lib\site-packages\crawl4ai\__init__.py", line 3, in <module>
    from .async_webcrawler import AsyncWebCrawler
  File "C:\Users\57682\PycharmProjects\pythonProject\venv\Lib\site-packages\crawl4ai\async_webcrawler.py", line 9, in <module>
    from .chunking_strategy import *
  File "C:\Users\57682\PycharmProjects\pythonProject\venv\Lib\site-packages\crawl4ai\chunking_strategy.py", line 6, in <module>
    from .utils import *
  File "C:\Users\57682\PycharmProjects\pythonProject\venv\Lib\site-packages\crawl4ai\utils.py", line 4, in <module>
    import html2text
  File "C:\Users\57682\PycharmProjects\pythonProject\venv\Lib\site-packages\html2text\__init__.py", line 11, in <module>
    from . import config
ImportError: cannot import name 'config' from partially initialized module 'html2text' (most likely due to a circular import) (C:\Users\57682\PycharmProjects\pythonProject\venv\Lib\site-packages\html2text\__init__.py)

**Comment by truonghoangnguyen** [comment]
Try download `config.py` file from url: `https://github.com/Alir3z4/html2text/blob/master/html2text/config.py` to `C:\Users\57682\PycharmProjects\pythonProject\venv\Lib\site-packages\html2text`

**Comment by unclecode** [comment]
I close this issue as it is unrelated to our library. It appears to be a conversion issue from HTML to text, and it seems that updating to the latest version will resolve the problem for that particular library. Thank you so much.
