### ISSUE TITLE
 Quick Start cant run 

### ISSUE THREAD

**Issue by BaoTan** [unclecode/crawl4ai#342]
Traceback (most recent call last):
  File "/home/paco/work_prjs/my_prjs/scrawler_xjp/main.py", line 11, in <module>
    asyncio.run(main())
  File "/home/paco/work_envs/dl_env/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/paco/work_envs/dl_env/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/paco/work_prjs/my_prjs/scrawler_xjp/main.py", line 6, in main
    result = await crawler.arun(url="https://www.nbcnews.com/business")
  File "/home/paco/work_envs/dl_env/miniconda3/lib/python3.9/site-packages/crawl4ai/async_webcrawler.py", line 185, in arun
    async with self._lock or nullcontext():
AttributeError: __aenter__

**Comment by Aclavelar** [comment]
I have just installed CrawlAi. I ran the test example and had similar error.

**Comment by deltacodepl** [comment]
I'm getting unhashable Error
[FETCH]... ↓ https://www.tapflo.com.pl/pompy-membranowe/seria-p... | Status: True | Time: 3.38s
[ERROR]... × https://www.tapflo.com.pl/pompy-membranowe/seria-p... | Error: 
┌───────────────────────────────────────────────────────────────────────────────┐
│ × Process HTML, Failed to extract content from the website:                   │
│ https://www.tapflo.com.pl/pompy-membranowe/seria-pe-i-ptfe, error:            │
│ unhashable type: 'list'                                                       │
└───────────────────────────────────────────────────────────────────────────────┘

**Comment by Themisstone** [comment]
I have the following error as shown below:

[ERROR]... × https://www.nbcnews.com/business... | Error: 
┌───────────────────────────────────────────────────────────────────────────────┐
│ × async_crawler_strategy.py:_crawleb(): Timeout 30000ms exceeded.             │
│   =========================== logs ===========================                │
│   "load" event fired                                                          │
│   ============================================================                │
└───────────────────────────────────────────────────────────────────────────────┘

**Comment by makispl** [comment]
Same here as well!

**Comment by unclecode** [comment]
Hey everyone

@BaoTan @Aclavelar Please update again to 0.4.21 in 2 - 3 hours and let me know please.

@deltacodepl @Themisstone  @makispl  Can you share your code snippet

**Comment by makispl** [comment]
Hi Hossein,

the script is the one attached (similar to the one I recently sent you to help me with extracting pricing plans and filtering features per tier). The issue is very rare, I have to admit.

In the meantime, I've created issue #349 [https://github.com/unclecode/crawl4ai/issues/349] regarding the deployment of my custom tool on crewai+ enterprise platform. I’d really appreciate it if you could help me with that.

I acknowledge that I’ve asked a lot, but I’ve tried a dozen of scrapers out there and crawl4AI is by far the best! My product deeply relies on this, I really need to overcome this issue 🙏🏼

Warm regards,

Ger

**Comment by unclecode** [comment]
Everyone please make sure to upgrade to 0.4.22 @BaoTan @deltacodepl @makispl  @Aclavelar

**Comment by unclecode** [comment]
> Hi Hossein, the script is the one attached (similar to the one I recently sent you to help me with extracting pricing plans and filtering features per tier). The issue is very rare, I have to admit. In the meantime, I've created issue #349 [#349] regarding the deployment of my custom tool on crewai+ enterprise platform. I’d really appreciate it if you could help me with that. I acknowledge that I’ve asked a lot, but I’ve tried a dozen of scrapers out there and crawl4AI is by far the best! My product deeply relies on this, I really need to overcome this issue 🙏🏼 Warm regards, Ger
> […](#)
> On 13 Dec 2024 at 2:46 PM +0200, UncleCode ***@***.***>, wrote: Hey everyone @BaoTan @Aclavelar Please update again to 0.4.21 in 2 - 3 hours and let me know please. @deltacodepl @Themisstone @makispl Can you share your code snippet — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Hi Ger, I will check your code very soon, hopefully today or tomorrow. I hope we can wrap it up and have a good example of Crawl4ai in our docs.

**Comment by Aclavelar** [comment]
> Everyone please make sure to upgrade to 0.4.22 @BaoTan @deltacodepl @makispl @Aclavelar

Hi

It is working now!

Thanks!!!

**Comment by unclecode** [comment]
You're welcome, please make sure to upgrade to 0.4.23 as well.
