### ISSUE TITLE
Full page pdf not working

### ISSUE THREAD

**Issue by nelzomal** [unclecode/crawl4ai#364]
I tried to run the [Full page pdf example](https://github.com/unclecode/crawl4ai/blob/ed7bc1909cdd49e23bc665d746f60a0b2fcaf594/docs/examples/full_page_screenshot_and_pdf_export.md?plain=1),

But got error, here is the full logs
```
[INIT].... → Crawl4AI 0.4.23
[EXPORT].. ℹ Exporting PDF and taking screenshot took 10.60s
[FETCH]... ↓ https://en.wikipedia.org/wiki/List_of_common_misco... | Status: True | Time: 12.29s
[SCRAPE].. ◆ Processed https://en.wikipedia.org/wiki/List_of_common_misco... | Time: 1901ms
[COMPLETE] ● https://en.wikipedia.org/wiki/List_of_common_misco... | Status: True | Total: 14.21s
Traceback (most recent call last):
  File "/Users/zhounan/me/prototype/cc_crawler/cc_search.py", line 34, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/zhounan/me/prototype/cc_crawler/cc_search.py", line 28, in main
    if result.pdf_data:
       ^^^^^^^^^^^^^^^
  File "/Users/zhounan/Library/Caches/pypoetry/virtualenvs/cc-crawler-NGi_SENK-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 892, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CrawlResult' object has no attribute 'pdf_data'
```

**Comment by zplusone** [comment]
yeah, i got this same error with python 3.9.6 and  crawl4ai version 0.4.23

**Comment by unclecode** [comment]
@nelzomal @zplusone I apologize for the mistake in the documentation. This happens when I rely on language models to save time 😒. It's not `pdf_data`; it's `result.pdf.` I have already updated the documentation, and I will make further updates when I release version 0.4.24. 

```python
import asyncio
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig, CacheMode
from crawl4ai.content_filter_strategy import PruningContentFilter
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator

async def main():
    # Configure the browser settings
    browser_config = BrowserConfig(headless=True, verbose=True)

    # Set run configurations, including cache mode and markdown generator
    crawl_config = CrawlerRunConfig(
        cache_mode=CacheMode.BYPASS,
        screenshot=True,
        pdf=True,
    )

    # Example 1: Using context manager (recommended for simple cases)
    print("\n=== Using Context Manager ===")
    async with AsyncWebCrawler(config=browser_config) as crawler:
        result = await crawler.arun(
            url='https://en.wikipedia.org/wiki/List_of_common_misconceptions',
            config=crawl_config
        )
        if result.success:
            # Save screenshot
            if result.screenshot:
                from base64 import b64decode
                with open(os.path.join(__location__, "screenshot.png"), "wb") as f:
                    f.write(b64decode(result.screenshot))
        
        # Save PDF
        if result.pdf:
            pdf_bytes = b64decode(result.pdf)
            with open(os.path.join(__location__, "page.pdf"), "wb") as f:
                f.write(pdf_bytes)


if __name__ == "__main__":
    asyncio.run(main())
```
