### ISSUE TITLE
Chromium distribution 'chrome' is not found

### ISSUE THREAD

**Issue by keyiis** [unclecode/crawl4ai#377]
My Environment:
OS: Windows 11
Python: 3.13.0
I have successfully run the following commands:
```
pip install crawl4ai
crawl4ai-setup # Setup the browser
```
Playwright was automatically installed in the directory D:\ProgramData\PLAYWRIGHT_BROWSERS, and I have also set the system environment variable PLAYWRIGHT_BROWSERS_PATH. However, when I run the sample code, I receive the following error:
```
playwright._impl._errors.Error: BrowserType.launch: Chromium distribution 'chrome' is not found at C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe
Run "playwright install chrome"
```
The official sample code I ran is as follows:
```
import asyncio
from crawl4ai import AsyncWebCrawler

async def main():
    # Create an instance of AsyncWebCrawler
    async with AsyncWebCrawler(verbose=True) as crawler:
        # Run the crawler on a URL
        result = await crawler.arun(url="https://www.bing.com")

        # Print the extracted content
        print(result.markdown)

# Run the async main function
asyncio.run(main())
```

**Comment by unclecode** [comment]
@keyiis I am a Mac user, and I will try your situation on a Windows machine. In the meantime, try the following steps and let me know how it goes.

1/ First, run the Playwright install command to install the required browser:
```
playwright install chromium
```

2/ Then modify your code to explicitly use Playwright's bundled Chromium instead of system Chrome:
```python
import asyncio
from crawl4ai import AsyncWebCrawler
from crawl4ai.async_configs import BrowserConfig

async def main():
    # Create browser config to use bundled Chromium
    browser_config = BrowserConfig(
        browser_type="chromium",  # Use Playwright's bundled Chromium
        chrome_channel=None  # Don't try to use system Chrome
    )
    
    # Create crawler instance with the config
    async with AsyncWebCrawler(browser_config=browser_config, verbose=True) as crawler:
        # Run the crawler on a URL
        result = await crawler.arun(url="https://www.bing.com")
        
        # Print the extracted content
        print(result.markdown)

# Run the async main function
asyncio.run(main())
````

Alternative Solution: If you prefer to use your system's Chrome browser, you can install Chrome and make sure it's in the default installation path. However, I recommend using the bundled Chromium approach above as it's more reliable across different environments.

**Comment by keyiis** [comment]
@unclecode Thks reply! When I run `playwright install chromium`,nothing happen.then i run your code,i get error
```
Traceback (most recent call last):
  File "D:\projects\ai\crawl4ai\test\test.py", line 21, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "D:\projects\ai\crawl4ai\test\test.py", line 13, in main
    async with AsyncWebCrawler(browser_config=browser_config,verbose=True) as crawler:
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\site-packages\crawl4ai\async_webcrawler.py", line 100, in __init__
    self.crawler_strategy = crawler_strategy or AsyncPlaywrightCrawlerStrategy(
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        browser_config=browser_config,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        logger=self.logger,
        ^^^^^^^^^^^^^^^^^^^
        **kwargs  # Pass remaining kwargs for backwards compatibility
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: crawl4ai.async_crawler_strategy.AsyncPlaywrightCrawlerStrategy() got multiple values for keyword argument 'browser_config'
```
then i modify your code
```
import asyncio
from crawl4ai import AsyncWebCrawler, BrowserConfig

async def main():
    browser_config = BrowserConfig(
        browser_type="chromium",  # Use Playwright's bundled Chromium
        chrome_channel=None  # Don't try to use system Chrome
    )
    # Modify here
    async with AsyncWebCrawler(config=browser_config,verbose=True) as crawler:
        # Run the crawler on a URL
        result = await crawler.arun(url="https://www.bing.com")

        # Print the extracted content
        print(result.markdown)

# Run the async main function
asyncio.run(main())
```
i get error
```
Traceback (most recent call last):
  File "D:\projects\ai\crawl4ai\test\test.py", line 21, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "D:\projects\ai\crawl4ai\test\test.py", line 13, in main
    async with AsyncWebCrawler(config=browser_config,verbose=True) as crawler:
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\site-packages\crawl4ai\async_webcrawler.py", line 131, in __aenter__
    await self.crawler_strategy.__aenter__()
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\site-packages\crawl4ai\async_crawler_strategy.py", line 501, in __aenter__
    await self.start()
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\site-packages\crawl4ai\async_crawler_strategy.py", line 508, in start
    await self.browser_manager.start()
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\site-packages\crawl4ai\async_crawler_strategy.py", line 291, in start
    self.browser = await self.playwright.chromium.launch(**browser_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\site-packages\playwright\async_api\_generated.py", line 14404, in launch
    await self._impl_obj.launch(
    ...<17 lines>...
    )
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\site-packages\playwright\_impl\_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.launch: Chromium distribution 'chrome' is not found at C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe
Run "playwright install chrome"
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001F2E930DC60>
Traceback (most recent call last):
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\base_subprocess.py", line 130, in __del__
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\base_subprocess.py", line 107, in close
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\proactor_events.py", line 109, in close
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\base_events.py", line 829, in call_soon
  File "D:\ProgramData\miniconda3\envs\crawl4ai-test\Lib\asyncio\base_events.py", line 552, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by unclecode** [comment]
@keyiis My baaaaaad, I promise to do 100 push ups!!, Its `config=browser_config` not `browser_config=browser_config`. Please try this code:

```python
mport asyncio
from crawl4ai import AsyncWebCrawler
from crawl4ai.async_configs import BrowserConfig

async def main():
    # Create browser config to use bundled Chromium
    browser_config = BrowserConfig(
        browser_type="chromium",  # Use Playwright's bundled Chromium
        chrome_channel=None  # Don't try to use system Chrome
    )
    
    # Create crawler instance with the config
    async with AsyncWebCrawler(config=browser_config, verbose=True) as crawler:
        # Run the crawler on a URL
        result = await crawler.arun(url="https://www.bing.com")
        
        # Print the extracted content
        print(result.markdown)

# Run the async main function
````

Happy New Year

**Comment by Umpire2018** [comment]
@keyiis 
Based on here, 

https://github.com/unclecode/crawl4ai/blob/78768fd714896c7666110a2df39d5359fd657e04/crawl4ai/async_configs.py#L103C1-L110C61

`None` or "chrome" will always evaluate to "chrome". So setting chrome_channel=None is redundant—looks like the default logic has it covered. Time to drop and give us those push-ups! 😄

**Comment by unclecode** [comment]
@Umpire2018 hahaha, Okay, now we have our new year entertainment, "collective push-ups"! :D

**Comment by Hamza5** [comment]
Hello @unclecode

Isn't there any way to use the Playwright-bundled Chromium? I don't want to install Chrome on my machine; I want to use the bundled Chromium because it's more portable and easy to install and use.

Another question: Is there a way to use Chromium-based browsers other than Chrome? Like Edge and Brave? Playwright supports them.

I am working on Debian 12.

**Comment by unclecode** [comment]
@Hamza5 Hey, we already install the Playwright-bundled Chromium for you. That means no need to install system-wide Chrome, you can run chromium out of the box. If you want to play with other Chromium variants (Edge, Brave, etc.), just pass the correct arguments in `BrowserConfig`. For example, to use Edge on Debian:

```python
from crawl4ai.async_configs import BrowserConfig
from crawl4ai.async_webcrawler import AsyncWebCrawler

browser_config = BrowserConfig(
    browser_type="chromium",
    chrome_channel="msedge",  # use Microsoft Edge channel
)

async with AsyncWebCrawler(config=browser_config) as crawler:
    # run crawls
    pass
```

If you have Brave installed, you can do something similar, just point to the Brave binary in `BrowserConfig.extra_args` or override the executable path if you want to try Brave. Otherwise, the default installation uses the bundled Chromium which is fully portable. (I havn't tested on Brave or Edge, mostly on chromium)

**Comment by Hamza5** [comment]
Thank you for your answer and time @unclecode , but for some reason, I still can't run the bundled Chromium (I will focus on this; no need for Edge or Brave at the moment).

Here is what I did:

1. Install Crawl4AI and Chromium:
```bash
pip install crawl4ai
playwright install chromium
```

2. Copy-pasted your example above:
```python
import asyncio
from crawl4ai import AsyncWebCrawler
from crawl4ai.async_configs import BrowserConfig

async def main():
    browser_config = BrowserConfig(
        browser_type="chromium",
        chrome_channel=None
    )
    
    async with AsyncWebCrawler(config=browser_config, verbose=True) as crawler:
        result = await crawler.arun(url="https://www.bing.com")
        print(result.markdown)

asyncio.run(main())
```

This results in the following error:
```
playwright._impl._errors.Error: BrowserType.launch: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
Run "playwright install chrome"
```

As you can see, it is _looking for **Chrome**_, and asking me to install it, but I don't want to use Chrome. I want to use **Chromium**.

Removing this `BrowserConfig` and trying again causes the same error. It always wants to run Chrome.

BTW, Chromium in my machine is installed in this location: `~/.cache/ms-playwright/chromium-1148/chrome-linux/chrome` 

If possible, can you tell me how to write a `BrowserConfig` to use it?

**Comment by unclecode** [comment]
@Hamza5 That's good you pointed this out. I found a small mistake in the code that caused all these issues. First, I changed and updated to the new version, which is 0.4.244. That will work, you dont need to set the chrome_channel, it will be always `chromium` by default.

However for current version just do this dirty trick:
```python
async def main():
    browser_config = BrowserConfig(
        browser_type="chromium",
        chrome_channel=None
    )
    browser_config.chrome_channel = None # 😅🤦‍♂️
    
    async with AsyncWebCrawler(config=browser_config, verbose=True) as crawler:
        result = await crawler.arun(url="https://www.bing.com")
        print(result.markdown)
```

So you can guess what went wrong! Anyway update to 0.4.244
