### ISSUE TITLE
Failed to install crawl4ai in windows 11

### ISSUE THREAD

**Issue by arcontechnologies** [unclecode/crawl4ai#38]
Hi,
I'm trying to install this library in virtual environment but ending with an building wheels error :
My environment : Windows 11
python : 3.11

used :  pip install "crawl4ai[all] @ git+https://github.com/unclecode/crawl4ai.git"
and then : pip install "crawl4ai @ git+https://github.com/unclecode/crawl4ai.git"

same error for both pips

```
 Traceback (most recent call last):
        File "D:\IntellicatCrawl\intellicatcrawl_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\IntellicatCrawl\intellicatcrawl_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\IntellicatCrawl\intellicatcrawl_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py", line 408, in run
          self.run_command("install")
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "C:\Users\mondorcast\AppData\Local\Temp\pip-build-env-ym7ctpyi\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 25, in run
        File "C:\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['D:\\IntellicatCrawl\\intellicatcrawl_env\\Scripts\\python.exe', '-m', 'pip', 'install', 'spacy', '--no-deps']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for crawl4ai
Failed to build crawl4ai
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (crawl4ai)
```

Any insight ?

**Comment by dtsunam** [comment]
I faced this same error when trying to install on windows and python 3.12.3. This appears to be a problem with latest version of pip not supporting the setup.py method of installation and trying to build the wheel. To resolve this I used python 3.11.5 and downgraded pip version.

```shell
python -m pip install pip==22.1.2
pip install -r .\requirements.txt
...
  Running setup.py install for crawl4ai ... done
```

**Comment by arcontechnologies** [comment]
@dtsunam It worked ! when downgrading pip to 22.1.2
thanks

**Comment by unclecode** [comment]
@arcontechnologies  Sorry for the long-delayed response. I believe I missed your issue. Since the day you posted until today, there have been tons of changes to the library. I'm very happy to see that we've faced a lot of interest, requests, and issues, and we're almost 14,000 stars. The entire project has been migrated to an asynchronous version. Here's a sample of the code that you can run quickly, and installation should be much easier than before. We've resolved many of the conflict issues. Please feel free to let me know if you encounter any problems.

```python
from crawl4ai import AsyncWebCrawler
async def simple_crawl():
    print("\n--- Basic Usage ---")
    async with AsyncWebCrawler(verbose=True) as crawler:
        result = await crawler.arun(url="https://www.nbcnews.com/business")
        print(result.markdown[:500]) 
```
