### ISSUE TITLE
i have some problem from the  file: crawl4ai/docs/examples /full_page_screenshot_and_pdf_export.md

### ISSUE THREAD

**Issue by mozou** [unclecode/crawl4ai#393]
hello.I saw this method and tried it:crawl4ai/docs/examples /full_page_screenshot_and_pdf_export.md
I used "CrawlerRunConfig()" as configuration management. The screenshot function is normal and can generate corresponding files. But I encountered some problems when operating PDF.

1. I found that it could not find: "pdf_data"
2. I found through debugging that the return value exists: "pdf", but the size of the PDF file obtained through this parameter is too small.

```python
import asyncio
import os
from base64 import b64decode

from crawl4ai import AsyncWebCrawler, CacheMode, CrawlerRunConfig


async def main():
    output_dir = './'
    url = 'https://en.wikipedia.org/wiki/List_of_common_misconceptions'
    crawler_config = CrawlerRunConfig(
        wait_for="body",
        cache_mode=CacheMode.BYPASS,
        pdf=True,  # if True,it exports the current page as a full PDF, capturing all of its content no matter the
        # length.
        screenshot=True,  # if True,and a PDF is already available, it directly converts the first page of that PDF
        # to an image for you—no repeated loading or scrolling.
    )

    async with AsyncWebCrawler() as crawler:
        # Request both PDF and screenshot
        result = await crawler.arun(
            url=url,
            config=crawler_config,
        )

        if result.success:
            # Save screenshot
            if result.screenshot:

                with open(os.path.join(output_dir, "screenshot.png"), "wb") as f:
                    img_bytes = result.screenshot
                    img_size_mb = len(result.screenshot) / (1024 * 1024)
                    print(f'the screenshot img file size:{img_size_mb}')
                    f.write(b64decode(img_bytes))

            # Check and save PDF, the parameter pdf_data is None
            if hasattr(result, 'pdf_data') and result.pdf_data:
                pdf_bytes = b64decode(result.pdf_data)
                # Print the pdf file size
                pdf_size_mb = len(result.pdf) / (1024 * 1024)
                print(f'the pdf_data file size:{pdf_size_mb}')
                with open(os.path.join(output_dir, "page.pdf"), "wb") as f:
                    f.write(pdf_bytes)
                print("PDF_data saved.")
            else:
                print("PDF_data is not available in the result.")

            # Check and save PDF, the parameter pdf_data is None
            if hasattr(result, 'pdf') and result.pdf:
                pdf_bytes = b64decode(result.pdf)
                # Print the pdf file size
                pdf_size_mb = len(result.pdf) / (1024 * 1024)
                print(f'the pdf file size:{pdf_size_mb}')
                with open(os.path.join(output_dir, "page.pdf"), "wb") as f:
                    f.write(pdf_bytes)
                print("PDF saved.")
            else:
                print("PDF is not available in the result.")

if __name__ == "__main__":
    asyncio.run(main())

```

Console print content:
```
  [INIT].... → Crawl4AI 0.4.23
  [WARNING]. ⚠ Both crawler_config and legacy parameters provided. crawler_config will take precedence.
  [EXPORT].. ℹ Exporting PDF and taking screenshot took 8.12s
  [FETCH]... ↓ https://en.wikipedia.org/wiki/List_of_common_misco... | Status: True | Time: 11.68s
  [SCRAPE].. ◆ Processed https://en.wikipedia.org/wiki/List_of_common_misco... | Time: 3391ms
  [COMPLETE] ● https://en.wikipedia.org/wiki/List_of_common_misco... | Status: True | Total: 15.08s
  the screenshot img file size:292.9688186645508
  PDF_data is not available in the result.
  the pdf file size:0.7151956558227539
  PDF saved.
```

If "if hasattr()" is not used for judgment, an exception message will be thrown directly:
```
line 892, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CrawlResult' object has no attribute 'pdf_data'
```

**Comment by mozou** [comment]
Even if I use the method in the file (without making any changes), I still get the same problem of "pdf_data" not being found.

```python
import asyncio
import os

from crawl4ai import AsyncWebCrawler, CacheMode


async def main():
    async with AsyncWebCrawler() as crawler:
        # Request both PDF and screenshot
        result = await crawler.arun(
            url='https://en.wikipedia.org/wiki/List_of_common_misconceptions',
            cache_mode=CacheMode.BYPASS,
            pdf=True,
            screenshot=True
        )

        if result.success:
            # Save screenshot
            if result.screenshot:
                from base64 import b64decode
                with open(os.path.join('./', "screenshot.png"), "wb") as f:
                    f.write(b64decode(result.screenshot))

            # Save PDF
            if result.pdf_data:
                pdf_bytes = b64decode(result.pdf_data)
                with open(os.path.join('./', "page.pdf"), "wb") as f:
                    f.write(pdf_bytes)


if __name__ == "__main__":
    asyncio.run(main())
```
Console print content:
```
[INIT].... → Crawl4AI 0.4.23
[EXPORT].. ℹ Exporting PDF and taking screenshot took 12.94s
[FETCH]... ↓ https://en.wikipedia.org/wiki/List_of_common_misco... | Status: True | Time: 20.89s
[SCRAPE].. ◆ Processed https://en.wikipedia.org/wiki/List_of_common_misco... | Time: 3333ms
[COMPLETE] ● https://en.wikipedia.org/wiki/List_of_common_misco... | Status: True | Total: 24.23s
Traceback (most recent call last):
  File "D:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\python-project\Crawl4AI -learning\examples\test.py", line 25, in main
    if result.pdf_data:
  File "E:\python-project\lib\site-packages\pydantic\main.py", line 892, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CrawlResult' object has no attribute 'pdf_data'
```

**Comment by unclecode** [comment]
@mozou Its my bad, the example has big, please follow this:

```python
import os, sys
__location__ = os.path.dirname(os.path.abspath(__file__))
__output__ = __location__ + "/output"

# Append parent directory to system path
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)

import asyncio
from crawl4ai import *


async def main():
    async with AsyncWebCrawler() as crawler:
        # Request both PDF and screenshot
        crawl_config = CrawlerRunConfig(
            cache_mode=CacheMode.BYPASS,
            pdf=True,
            screenshot=True
        )
        result = await crawler.arun(
            # url='https://en.wikipedia.org/wiki/List_of_common_misconceptions',
            url='https://crawl4ai.com',
            config=crawl_config
        )
        
        if result.success:
            # Save screenshot
            if result.screenshot:
                from base64 import b64decode
                with open(os.path.join(__output__, "screenshot.png"), "wb") as f:
                    f.write(b64decode(result.screenshot))
            
            # Save PDF
            if result.pdf:
                pdf_bytes = b64decode(result.pdf)
                with open(os.path.join(__output__, "page.pdf"), "wb") as f:
                    f.write(pdf_bytes)

if __name__ == "__main__":
    asyncio.run(main())
```

The extracted data for the PDF is already a binary file, so it doesn't need conversion to base 64. I'm working hard on a new set of documentation, and I believe many of these issues will be fixed, making the documentation very valid. Please stay tune.

**Comment by mozou** [comment]
Thanks, the problem has been solved. But your example seems to have some problems. It should be written directly to the file instead of converted to base 64.
```python
# the original code
if result.pdf:
  pdf_bytes = b64decode(result.pdf)
  with open(os.path.join(__output__, "page.pdf"), "wb") as f:
      f.write(pdf_bytes)

# the success generate pdf file code, it doesn't need conversion to base 64
if result.pdf:
  # pdf_bytes = b64decode(result.pdf)
  with open(os.path.join(__output__, "page.pdf"), "wb") as f:
      f.write(result.pdf)
```
If the method is modified like this, even the original wiki:"https://en.wikipedia.org/wiki/List_of_common_misconceptions" link can generate a pdf file

**Comment by unclecode** [comment]
@mozou I am so sorry, I actually was talking about exactly this, that you dont need to use `b64decode` but again I pasted the same code with same issues, shame on me :D:D:D

**Comment by mozou** [comment]
> @mozou非常抱歉，我实际上正在谈论这个，你不需要使用，`b64decode`但我再次粘贴了相同的代码，存在相同的问题，我真丢脸：D：D：D

Haha, that's nothing.

**Comment by unclecode** [comment]
Thx
