### ISSUE TITLE
NameError: name 'MODEL_REPO_BRANCH' is not defined

### ISSUE THREAD

**Issue by Kronomono** [unclecode/crawl4ai#68]
I was trying to run crawl4ai-download-models   as I downloaded using the full installation 
pip install "crawl4ai[all] @ git+https://github.com/unclecode/crawl4ai.git"

```
PS C:\Users\Krono\Desktop\Test_project\webcrawler> crawl4ai-download-models   
[LOG] Welcome to the Crawl4AI Model Downloader!
[LOG] This script will download all the models required for Crawl4AI.
[LOG] Downloading text classifier...
Traceback (most recent call last):
  File "C:\Users\krono\anaconda3\envs\a\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\krono\anaconda3\envs\a\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\krono\anaconda3\envs\a\Scripts\crawl4ai-download-models.exe\__main__.py", line 7, in <module>
  File "C:\Users\krono\anaconda3\envs\a\lib\site-packages\crawl4ai\model_loader.py", line 276, in main
    download_all_models(remove_existing=args.remove_existing)
  File "C:\Users\krono\anaconda3\envs\a\lib\site-packages\crawl4ai\model_loader.py", line 263, in download_all_models
    _, device = load_text_multilabel_classifier()
  File "C:\Users\krono\anaconda3\envs\a\lib\site-packages\crawl4ai\model_loader.py", line 150, in load_text_multilabel_classifier
    return load_spacy_model(), torch.device("cpu")
  File "C:\Users\krono\anaconda3\envs\a\lib\site-packages\crawl4ai\model_loader.py", line 201, in load_spacy_model
    branch = MODEL_REPO_BRANCH
NameError: name 'MODEL_REPO_BRANCH' is not defined
```
i run into the same error when trying to run
```
from crawl4ai.extraction_strategy import CosineStrategy
from crawl4ai import WebCrawler

crawler = WebCrawler()
crawler.warmup()

# Define extraction strategy
strategy = CosineStrategy(
    semantic_filter="finance economy stock market",
    word_count_threshold=10,
    max_dist=0.2,
    linkage_method='ward',
    top_k=3,
    model_name='BAAI/bge-small-en-v1.5'
)

# Sample URL
url = "https://www.nbcnews.com/business"

# Run the crawler with the extraction strategy
result = crawler.run(url=url, extraction_strategy=strategy)
print(result.extracted_content)
```
I ended up going through the file itself and saw 
```
       # branch = "main"
        branch = MODEL_REPO_BRANCH 
```
on lines 200 and 201, I ended up trying to set branch = "main" 
but ended up with a different error 
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\krono\\.crawl4ai\\crawl4ai\\.git\\objects\\pack\\pack-e6d73d2789a8627605ba2da4e721c44131c662e7.idx'
going further down the error it wants you to delete the insides of the entire pack folder. 

You could also go and comment out the lines of code on lines 
208 - 210
```
        if Path(repo_folder).exists():
            shutil.rmtree(repo_folder)
            shutil.rmtree(model_folder)
```
Which i tried and I ended up with
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\krono\\.crawl4ai\\models/reuters'

**Comment by unclecode** [comment]
Thanks for the report, @Kronomono . Please reinstall the newer version v0.2.77, as the issue should be resolved. Let me know if you encounter any other problems.

**Comment by Kronomono** [comment]
No issues on my end, thank you.
